---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hugo.
--- DateTime: 12/04/2025 10:10 PM
---

print("Hugo's test initiated")

for i = 0, 2 do
    local name = "tree" .. i
    scene:loadBoxModelToRegistry("Assets/game_tree1_dead_small/tree1.gltf", name)
end

scene:setEntityPosByName("tree0",50,10,50)
scene:setEntityPosByName("tree1",-50,10,50)
scene:setEntityPosByName("tree1",-50,10,-50)

print("Hugo's test finished")