---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hugo.
--- DateTime: 12/04/2025 10:10 PM
---

print("Hugo's test initiated")
scene:loadBoxModelToRegistry("Assets/game_jeep/jeep.gltf")
scene:loadBoxModelToRegistry("Assets/game_jeep/jeep.gltf")
scene:loadBoxModelToRegistry("Assets/game_jeep/jeep.gltf")
print("i tried to load 3 jeeps")